config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :jobs, only: [:show, :new, :create]
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :participants

  validates :meetup_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :description, presence: true
  validates :time, presence: true
  validates :url, presence: true
  validates :status, presence: true
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true, url: true
  validates :location, presence: true
end

app/models/meetup.rb
class Meetup
  GROUP_ID = '1700659'
  GROUP_SLUG = 'rubyonrails-ch'

  def client
    @client ||= RubyMeetup::ApiKeyClient.new
  end

  def events
    call_api('events', group_id: GROUP_ID, page: 5)
  end

  def participants(event_meetup_id)
    call_api('rsvps', event_id: event_meetup_id)
  end

  private

  def call_api(path, params)
    result = client.get_path("/2/#{path}", params)
    JSON.parse(result, object_class: OpenStruct).results
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :event

  validates :meetup_id, presence: true
  validates :name, presence: true
  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where('time > ?', Time.zone.now.beginning_of_day).order(:time)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :url, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def meetup_url
    "http://www.meetup.com/#{Meetup::GROUP_SLUG}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def maps_url(query)
    "http://maps.google.com/maps?q=#{query}"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/_jobs.html.haml
%ul.jobs.list-unstyled
  - @jobs.each_with_index do |job, index|
    - is_next = index == 0
    %li{ class: ['job', 'row', ('next' if is_next)] }
      .col-md-2.text-right
        %span.label.label-default= job.time.to_s(:short)
      .col-md-10
        - job_link = link_to job.name, job.url
        - unless is_next
          %h4= job_link
        - else
          %h4= job_link
          %p= link_to job.address, maps_url(job.address), class: 'address' if job.address

          = render 'participants', participants: job.participants

  %li.job.row.more
    .col-md-2
    .col-md-10
      = link_to 'visit meetup for more', meetup_url

app/views/home/_participants.html.haml
.participants
  - participants.each do |participant|
    - if participant.image_url
      .participant
        = image_tag participant.image_url, alt: participant.name, title: participant.name, size: '40x40', class: "participant status-#{participant.status}"
        = participant.name

app/views/home/index.html.haml
#infnengage in projects or just to have a beer? Look no further.

#events.tile
  %h2 upcoming events
  .events-container
    - @events.each_with_index do |event, index|
      - is_next = index == 0
      %div{ class: ['event wrapper', ('next' if is_next)] }
        .ruby= image_tag 'RubyonRails_gem_v01-01.svg'
        .event.link
          - event_link = link_to event.name, event.url
          %h3= event_link
          %p.address
            - if event.address
              =link_to event.time.to_s(:short) + ' | ' + event.address, maps_url(event.address)
            - else
              = event.time.to_s(:short) + ' | to be defined'

        .join-meetup{ id: event.meetup_id }
          Attend

        .participants-toggle
          = image_tag 'ic_people_48px.svg'
          = render 'participants', participants: event.participants

  .read-more
    = link_to 'visit meetup for more', meetup_url

#topics.tile
  .content
    %h2 Next / Previous Topics
    %p please post here which topics you would want to hear about it soon.

#jobs.tile
  .content
    %h2 Jobs
    - @jobs.each do |job|
      = render 'jobs/job', job: job

#sponsors.tile
  .content
    %h2 Sponsors
    %p We would like to thank our sponsors for the great support they provide us so that we can regularly held events in their locations.

    .sponsor= image_tag 'sponsors/panter.png', id: 'patner'
    .sponsor= image_tag 'sponsors/impact-hub.png', id: 'impact-hub'
    .sponsor= image_tag 'sponsors/ungleich.png', id: 'ungleich'
    .sponsor= image_tag 'sponsors/simplificator.png', id: 'simplificator'

app/views/home/join_meetup.js.erb
"you sucessfully joined the meetup"

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :title, placeholder: :title
  .field
    = f.text_field :url, placeholder: :url
  .field
    = f.text_field :location, placeholder: :location
  .actions
    = f.submit 'Save'

app/views/jobs/_job.haml
.job-wrapper
  .expand-jobs
    =image_tag 'ic_arrow_forward_36px.svg'
  %h3= job.title
  %p= job.short_description
  %b= link_to job.url, job.url
  .long-description= simple_format(job.description)

app/views/jobs/_job.html.haml
.job-wrapper
  .expand-jobs
    =image_tag 'ic_arrow_forward_36px.svg'
  %h3= job.title
  %p= job.location
  %b= link_to job.url, job.url

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @jobs.each do |job|
      %tr
        %td= job.title
        %td= link_to 'Show', job
        %td= link_to 'Edit', edit_job_path(job)
        %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
.tile
  .content
    %h2 New job

    = render 'form'

    .back
      = link_to 'Back', root_path

app/views/jobs/show.haml
.tile
  .content
    %h2 This job was posted on the Ruby on Rails Switzerland website.

    %p#notice= notice

    = render partial: 'job', locals: { job: @job }

    %p
      = link_to 'Back to Ruby on Rails Switzerland', root_path
    %p
      = link_to 'Delete this job', job_path(@job), data: { confirm: 'do you really want to delete this job?' }, method: :delete

app/views/jobs/show.html.haml
.tile
  .content
    %h2 This job was posted on the Ruby on Rails Switzerland website.

    %p#notice= notice

    = render partial: 'job', locals: { job: @job }

    %p
      = link_to 'Back to Ruby on Rails Switzerland', root_path
    %p
      = link_to 'Delete this job', job_path(@job), data: { confirm: 'do you really want to delete this job?' }, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html{:lang => I18n.locale, :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title Ruby on Rails user group Schweiz
    = csrf_meta_tags
    = stylesheet_link_tag :application

    %link{href: asset_url('favicon.png'), rel: 'icon', type: 'image/png'}/

    %meta{content: 'IE=edge,chrome=1', 'http-equiv': 'X-UA-Compatible'}/
    %meta{content: "text/html; charset=utf-8", 'http-equiv': "Content-Type"}/

    %meta{name: "apple-mobile-web-app-capable", :content=>"yes"}
    %meta{name: "viewport", content: "width=device-width, minimum-scale=1.0, initial-scale=1.0"}

  %body
    .container
      %header
        .logo
          = image_tag 'RubyonRails_Icon_v01-01.svg', :id => 'logo'
        %title
          %h1 Ruby on Rails Meetups
          .lead Schweiz

    .spinner
      .hexdots-loader
        Loading…

    = yield

    = javascript_include_tag 'application'